### ISSUE TITLE
[Suggestion] Configurable list of items to enable features for.

### ISSUE THREAD

**Issue by Darkmega18** [Fourmisain/AxesAreWeapons#13]
Rather than having a large blanket config option for "all weapons are tools" can you make it a list of item id strings for which the mod will enable for for selectively? 
For example I could configure shovels to be weapons too so people can be shovel knight or something but not pickaxes or hoes.
or I could be really funky and allow an exotic take on melee bow/crossbow combat with enchants and shooting if the bow itself looks like it has sharp bits which can be weaponized. rather than now ending up with literally everything weaponizable.

**Comment by Fourmisain** [comment]
The "All Tools Are Weapons" option was never really meant to be a thing in the first place.
Originally I only added it because someone wanted to mod tools into weapons as well (e.g. give hoes back their shredding ability they once had, maybe give shovels some stun mechanic etc). It made sense to add it from a mod compatibility stance.

Your idea of melee (cross) bows wouldn't work without deeper changes to the game, as they do not have attack damage or even durability loss for that matter. For melee they work like every other regular item or bare hands, which also means no enchantments apply. (Meaning that, sadly, a Sharpness V potato won't deal additional damage).

So using a list of item ids would not allow for more items to be "weaponized". It would also be a nightmare to configure when you got dozens/hundreds of modded items.

Originally I was thinking of splitting up the option into shovels, hoes and pickaxes, but decided against it because realistically it wouldn't really change all that much.
A shovel, hoe or pickaxe will not become a "true" weapon just by having Sharpness on it.
Their stats are still much worse than swords or axes, so it only really makes sense if you mod those items further.

So yeah, I'm currently not convinced. I might come around and split up the option at some point.
Not sure when that is, the outsides currently look like 🔥🔥🔥🔥

**Comment by Darkmega18** [comment]
don't worry, it works in my pack. cause war dance. I make the crossbows only have 1 attack rate with attributizer so to not be spammy but they deal posture damage and you can actually deflect projectiles with one out due to the parrying mechanics.

Sharpness does indeed work on random stuff. I've seen sharpness 10 literal wooden signs in old super hostile maps deal better than diamond sword damage and apply fire aspect etc. unless it was changed in recent game versions. but I dunno why they'd do such a thing.
and mods which add flat damage bonuses via artifacts and curios exist, allowing you to essentially transfer your direct bonus melee damage into the crossbow or bow to bonk with it, and then shoot afterwards.

Likewise, our shovels are actually very heavy and deal a lot of posture damage, essentially becoming vanilla minecraft equivalents of hammers. While pickaxes are more stealth oriented with higherish stealth damage multipliers. So although not true melee weapons, they can be salvaged, and crazy people like myself exist.

You just gotta put some imagination into it and have the right mods to end up screwing around with ideas like these.

> So using a list of item ids would not allow for more items to be "weaponized". It would also be a nightmare to configure when you got dozens/hundreds of modded items.

Can I raise you a "ok buddy, I'm gonna shit yourself".
https://docs.google.com/spreadsheets/d/1H7CFZ4_YiyuQjOGueJ5JQm0fELgh58JiidYFoRZC2K0/
https://docs.google.com/spreadsheets/d/1qBzwZQshb9WBc1IIoq0PKKcRa1vBlylXkWOYBh3zlw8
Behold, the War Dance+cloak and dagger Weapon and Armor datapack configuration files... which have spanned two modpacks and a lot of trialed mods I don't even really use anymore from between myself and the owner. ~~_you don't know what hell is when it comes to config files._~~ it's both a curse and my experimental happy place for my favorite combat mod. ;)

**Comment by Fourmisain** [comment]
[Give this a try.](https://github.com/Fourmisain/AxesAreWeapons/releases/download/debug/AxesAreWeapons-1.7.0-forge-1.19.2.jar)

I split it up into Pickaxes, Shovels, Hoes, Ranged Weapons and an additional list of item IDs.
With this I was able to get a Bane of Arthropods Fishing Rod in the Enchanting Table.
This will probably be the release version once I double check everything tomorrow or so (and do more version ports).

>Sharpness does indeed work on random stuff last I knew. I've seen sharpness 10 literal wooden signs in old super hostile maps deal better than diamond sword damage and apply fire aspect etc. unless it was changed in recent game versions. but I dunno why they'd do such a thing.

Now that you mention it, I do remember the good ol' Knockback 100 sticks.
Just tested it on 1.19.4 and the Sharpness X potato is indeed mightier than the sword.
Not sure where my confusion came from - I think it's because enchantments don't work on Enchanted Books themselves.

Note however that most items are not enchantable, so the item ID list won't allow for stuff like Sharpness potatoes.

> > It would also be a nightmare to configure when you got dozens/hundreds of modded items.
>
> Wasn't really asking for any old random items. But really just tool or weaponry related stuff that can somewhat make sense.

What I meant is that you can easily have dozens or hundreds of tool and weapon related items. When you simply want all shovel items to be weapons, you'd have to put every single one on that list manually, hence I added switches for the bigger categories.
(I was also thinking about item tags, but they are unreliable, especially on Forge I think.)

> Behold, the War Dance+cloak and dagger Weapon and Armor attributizer datapack configuration spreadsheets with which I make the jsons...

That's pretty much what I was on about... 😄

> You just gotta put some imagination into it and have the right mods to end up screwing around with ideas like these.

You know, when I was creating Axes Are Weapons I was thinking of making **all** enchantments configurable for **all** items, since there's so many mods which do this in a limited scope but you never quite get _exactly_ what you want.
(With the current system you can't say "I want shovels and hoes to be weapons and shovels should have Knockback **but not hoes**".)

I ultimately decided against that because it's simply out of scope for what Axes Are Weapons is meant to be, would be a huge maintenance burden when you take into account modded enchantments and ways to enchant plus it'd be a pain writing the config UI for that. (Writing the UI for Falling Leaves once was enough. Even for this "small" change I had to copy some of the complex code over.)

At least I added a separate option for Looting (cross) bows, as this seemed very reasonable when you don't want melee bows.

**Comment by Darkmega18** [comment]
Thank you very much. Glad I managed to convinced you, or some variation on it. xD
Although it's a touch late for myself to go back to the modpack testing and work, I'll give it a shot tomorrow. :)
