### ISSUE TITLE
Axes no longer cut tree's properly

### ISSUE THREAD

**Issue by keybladegames** [Fourmisain/AxesAreWeapons#14]
It's good to finally get the enchantments I always wanted on my axe but when I decided to test cutting tree's to make sure that didn't change I noticed I cant cut tree's as fast as I should. It's a netherite axe, it cuts fast but now it's the same speed as trying to cut a tree with a sword.

**Comment by Fourmisain** [comment]
Can't reproduce. 
Only cobwebs should ever be affected by any mining speed changes, and that is turned off by default, so I'm not sure what you're seeing.

What Minecraft version are you playing on? Fabric or Forge? Are you using the newest Axes Are Weapons (1.7.1)?
What other mods have you installed?

**Comment by keybladegames** [comment]
> 

I'm on 1.19.2 forge.

**Comment by Fourmisain** [comment]
Can't reproduce this on there either, no matter what settings I use. The axe is as fast as it should be and Efficiency works too:

https://github.com/Fourmisain/AxesAreWeapons/assets/8464472/39f0502c-cd9e-401c-87f2-e9b411f5fe3d

I can't help you if you don't give more information, so please answer these questions too:

> Are you using the newest Axes Are Weapons (1.7.1)?
>
> What other mods have you installed?

Either I'm completely misunderstanding what you are asking, or there's conflict or issue with another mod.
I'm definitely going to need a full mod list.

**Comment by keybladegames** [comment]
I dunno. I got a gilded netherite sword and axe. They both cut down the tree at the same speed. I have another mod that tells you what things are and shows you the time to break cause it fills up the outline of the box with the name and the sword and axe break at the same speed.

**Comment by Fourmisain** [comment]
What do you mean you dunno?
You can see what mods you have installed by pressing "Mods" on the title screen.
I need the names of all your installed mods, especially the one adding the gilded netherite.
If you are playing a modpack, you can just send me a link to that.

Though to be honest, I don't believe this is actually an issue with this mod, so please try the following:
Uninstall Axes Are Weapons and test if the issue is still happening.
If it still happens, then the issue is unrelated to this mod and you have to search elsewhere.

**Comment by Fourmisain** [comment]
Closed due to missing info.
