### ISSUE TITLE
Axes Are Weapons Allowing Wrong Enchants

### ISSUE THREAD

**Issue by RotokEralil** [Fourmisain/AxesAreWeapons#2]
Hello!
Using AxesAreWeapons-1.5.1-fabric [1.17 and 1.18], on Fabric for 1.18.1, the mod allows armor enchants and crossbow/bow enchants to be applied to axes in survival.  
I am unsure what these two config settings are:
**	"enableForEnchantingTable": true,
	"enableDamageInEnchantingTable": true,
**
Would this cause it?

**Comment by Fourmisain** [comment]
No, that would definitely not cause it, so let us see what's going wrong.

First of all, are you *sure* you are actually in survival mode? Because you can apply any enchantment to any item when in creative mode.

If that's not it, I'll need a lot more info:

 - Does the issue happen without Axes Are Weapons?
 - Is this about the Anvil or the Enchanting Table?
 - Which other mods do you have installed? (Especially mods touching Enchantments/Anvil/Enchanting Table are relevant.)
 - Which enchantments _specifically_ are we talking? Are they modded?
 - Is the axe modded?

Also, to understand those settings better, it's best to look at them in Mod Menu:
![settings](https://user-images.githubusercontent.com/8464472/151118751-01aad070-ccf8-4c2e-a159-f0ee4ed912cc.png)

`enableForEnchantingTable` is "Enable the above in the Enchanting Table too", so in this case, Looting would appear for axes in the Enchanting Table as well.
`enableDamageInEnchantingTable` is "Enable Damage Enchantments for Axes in the Enchanting Table", which adds Sharpness, Smite and Bane of Arthropohs for axes to the Enchanting Table.

**Comment by RotokEralil** [comment]
It was some wonky interaction with a trident enchant datapack that got left in whenever I would recreate worlds to test my mods (apologies).
