### ISSUE TITLE
Allow breaking cobwebs as fast as swords

### ISSUE THREAD

**Issue by p3lim** [Fourmisain/AxesAreWeapons#4]

**Comment by Fourmisain** [comment]
k, I think the answer to both of those questions is yes.

Breaking Cobwebs fast but not having them drop String feels weird because blocks being broken fast communicates you're using the proper tool, hence it should also drop the String.

While it is kinda weird mining Cobwebs with a Pickaxe, Shovel or Hoe, the same can be said about them being used as weapons and since all other options of this mod apply to them equally, so should this option for consistency.

I got working versions for Fabric 1.16 and 1.17 now, the latter which seems to work fine on 1.18 and 1.19 too.
Forge needs some testing and I need to get that publishing script going (because I need to stop manually releasing 5+ builds for each small change onto multiple platforms).
Hopefully tomorrow.

**Comment by Fourmisain** [comment]
New versions are up!

Aaand I just noticed this doesn't work server-only.
Singleplayer is fine but for multiplayer the clients need to have the mod installed with the setting enabled, else it'll break slowly.
